<div id="views">
		<h2>View Rendering</h2>
		<p>
			See the <code>org.springframework.samples.mvc.views</code> package for the @Controller code
		</p>
		<ul>
			<li>
				<a href="<c:url value="/views/html" />">HTML generated by JSP template</a>
			</li>
		</ul>	
		<ul>
			<li>
				<a href="<c:url value="/views/viewName" />">DefaultRequestToViewNameTranslator convention</a>
			</li>
		</ul>	
		<ul>
			<li>
				<a href="<c:url value="/views/pathVariables/bar/apple" />">Using path variables in a view template</a>
			</li>
		</ul>
		<ul>
			<li>
				<a href="<c:url value="/views/dataBinding/bar/apple" />">Data binding with URI variables</a>
			</li>
		</ul>
	</div>